Millestone #1: WebPack and first layout
GuilhermeGiachellin/To-Do-List pull request #1
Opened 2021-07-14 21:38 UTC by GuilhermeGiachellin

## What was done in this Milestone:

- Add WebPack to the repo.
- Created a simple layout.
- Array of objects that contains the information of the list.
- All the list is generated via JS.

2021-07-14 22:52 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @GuilhermeGiachellin :wave:

_Tis milestone is almost complete as most of the tasks have been implemented :handshake:_

- Your PR title, summary and commit messages looks okay :ok_hand: 
- All linter checks are running with no errors :100: 

__However, you need to make some required changes before moving on to the next assignment.__
> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it :blush: 

### **Required Changes** :recycle: 
Check the comments under the review.

### **Optional Changes** :zap: 
_Every comment with the **OPTIONAL** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

2021-07-14 22:52 UTC, teekaytech commented on webpack.config.js
>      new HtmlWebpackPlugin({
- [ ] You need to configure the basic commands for building Webpack in development and production mode using the `package.json` file. I believe you've done something similar in your Webpack exercise. We should be able to set up and run Webpack devserver with no errors, using the configuration. At the moment, package.json is completely missing in your project. Kindly fix this.

2021-07-14 22:52 UTC, teekaytech commented on src/index.js
> +console.log(list.length);
- [ ] Kindly remove this console statement: they make your code look messy. Always double-check to ensure that you remove all console log statements in the future before you commit your changes.

2021-07-14 22:52 UTC, teekaytech commented on src/style.css
> +}
- [ ] Also, you should ensure that the CSS created is used to style the list using the [captured video](https://www.youtube.com/watch?v=AcUd-_Yjjqg). I can see that you've done this to a reasonable extent. However, you have to align your booklist to the center of the page, as we have it in the video.

2021-07-14 22:52 UTC, teekaytech commented on README.md
>  ## What was built in this project:
**OPTIONAL**

- [ ] Kindly update your Readme file
- I strongly suggest you add the `Getting Started` section, where you state the instructions and code samples that will be needed to clone your project, install its dependencies, and starting the project on a dev environment.

2021-07-15 02:38 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @GuilhermeGiachellin🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 13:06 UTC, merged